### PR TITLE
Stage updated

### PR DESCRIPTION
**Pull request by JaciCode**
Hello commandos, I've updated code in stage branch, please review and approve

### CODE REVIEW

**Comment by EkaetteHart** [comment]
nice work!

**Review by EkaetteHart — APPROVED** [review]

**Comment by EkaetteHart** [comment]
great job Engr

**Comment by dannyafari** [comment]
nice job Engineer!

**Comment by DebowaleAjayi** [comment]
Good-to-go, Jacicode!

**Pull request merged**
